/**
 * Web App Template for Build.io
 *
 * This template has two modes:
 *   1. (default) Zero-dependency mode — uses Node's built-in `http` module.
 *   2. (upgraded) Express + MongoDB — after you run `npm install` locally.
 *
 * To switch to mode 2 locally:
 *   npm install express mongoose
 *   git add -A
 *   git commit -m "Add express and mongoose"
 *   git push build main
 *
 * Build.io needs a package-lock.json (generated by `npm install`) to run
 * `npm ci` during deploy.  Without one it skips dependency installation,
 * which is why this file must work with only Node built-ins by default.
 */

const http = require("http");
const url  = require("url");

// ============================================================
// CONFIGURATION
// ============================================================
const PORT     = process.env.PORT || 3000;
const env      = process.env.NODE_ENV || "development";
const appName  = process.env.APP_NAME || "my-app";
const mongoUrl = process.env.MONGODB_URL;

// ============================================================
// OPTIONAL: Express + Mongoose (loaded only when installed)
// ============================================================
let express, mongoose, app, Item, connected = false;

try {
  express  = require("express");
  mongoose = require("mongoose");
} catch (_) {
  // Express / Mongoose not installed yet — that's fine, we'll
  // serve a helpful landing page with plain Node http.
}

// If express IS available, set up the Express app + routes
if (express && mongoose) {
  app = express();
  app.use(express.json());
  app.use(express.urlencoded({ extended: true }));

  // Request logger
  app.use((req, _res, next) => {
    console.log(`[${new Date().toISOString()}] ${req.method} ${req.url}`);
    next();
  });

  // Mongoose model
  const ItemSchema = new mongoose.Schema({
    name      : { type: String, required: true },
    completed : { type: Boolean, default: false },
    createdAt : { type: Date, default: Date.now }
  });
  Item = mongoose.model("Item", ItemSchema);

  async function connectDB() {
    if (!mongoUrl) return;
    try {
      await mongoose.connect(mongoUrl);
      connected = true;
      console.log("✅  MongoDB connected");
    } catch (err) {
      console.error("❌  MongoDB connection failed:", err.message);
    }
  }

  // Routes
  app.get("/", async (_req, res) => {
    let count = 0;
    if (connected) {
      try { count = await Item.countDocuments(); } catch (_) {}
    }
    res.json({
      message: `Welcome to ${appName}!`,
      mode: "express",
      environment: env,
      database: connected ? "connected" : mongoUrl ? "disconnected" : "not configured",
      itemCount: count,
      endpoints: {
        health: "GET /health",
        items: {
          list:   "GET    /api/items",
          create: "POST   /api/items",
          get:    "GET    /api/items/:id",
          update: "PUT    /api/items/:id",
          delete: "DELETE /api/items/:id"
        }
      }
    });
  });

  app.get("/health", async (_req, res) => {
    let dbStatus = "not configured";
    if (mongoUrl) {
      dbStatus = connected && mongoose.connection.readyState === 1 ? "healthy" : "unhealthy";
    }
    res.status(200).json({ status: "healthy", database: dbStatus, uptime: process.uptime() });
  });

  const dbGuard = (_req, res) => res.status(503).json({ error: "Database not configured" });

  app.get("/api/items",  connected ? async (_req, res) => res.json({ count: (await Item.find().sort({createdAt:-1})).length, items: await Item.find().sort({createdAt:-1}) }) : dbGuard);
  app.post("/api/items", connected ? async (req, res) => {
    if (!req.body?.name) return res.status(400).json({ error: "name is required" });
    res.status(201).json({ message: "Created", item: await Item.create({ name: req.body.name }) });
  } : dbGuard);
  app.get("/api/items/:id",  connected ? async (req, res) => { const item = await Item.findById(req.params.id); item ? res.json({item}) : res.status(404).json({error:"Not found"}); } : dbGuard);
  app.put("/api/items/:id",  connected ? async (req, res) => { const item = await Item.findByIdAndUpdate(req.params.id, { name: req.body.name, completed: req.body.completed }, { new: true }); item ? res.json({message:"Updated", item}) : res.status(404).json({error:"Not found"}); } : dbGuard);
  app.delete("/api/items/:id", connected ? async (req, res) => { const item = await Item.findByIdAndDelete(req.params.id); item ? res.json({message:"Deleted", item}) : res.status(404).json({error:"Not found"}); } : dbGuard);

  app.use((_req, res) => res.status(404).json({ error: "Not found" }));

  // Start Express server
  async function main() {
    await connectDB();
    const server = app.listen(PORT, () => {
      console.log("\n" + "=".repeat(50));
      console.log(` 🚀  ${appName}  (Express mode)`);
      console.log(` 📍  http://localhost:${PORT}`);
      console.log(` 🔧  ${env}`);
      if (!connected && mongoUrl) console.log(` ⚠️  DB disconnected`);
      else if (!connected)        console.log(` 💡  Run: bld addons:create donkey-to-go`);
      console.log("=".repeat(50) + "\n");
    });
    process.on("SIGTERM", () => server.close(async () => { if (connected) await mongoose.connection.close(); process.exit(0); }));
  }
  main().catch((err) => { console.error("Failed to start:", err); process.exit(1); });

// ============================================================
// FALLBACK: Plain Node http (zero dependencies)
// ============================================================
} else {
  const server = http.createServer((req, res) => {
    res.setHeader("Content-Type", "application/json");

    const parsed = url.parse(req.url, true);

    // --- Health (required by Build.io) ---
    if (parsed.pathname === "/health") {
      res.writeHead(200);
      res.end(JSON.stringify({ status: "healthy", uptime: process.uptime(), timestamp: new Date().toISOString() }));
      return;
    }

    // --- Home landing page ---
    res.writeHead(200);
    res.end(JSON.stringify({
      message: `Welcome to ${appName}!`,
      mode: "no dependencies",
      environment: env,
      note: "Express and Mongoose are not installed yet.",
      instructions: [
        "1. Run 'npm install' locally to add dependencies",
        "2. Commit package-lock.json + node_modules",
        "3. git push build main"
      ],
      quickStart: {
        addMongoDB: "bld addons:create donkey-to-go && bld ps:restart",
        installLocally: "npm install express mongoose",
        deploy: "git add -A && git commit -m 'Add deps' && git push build main"
      }
    }, null, 2));
  });

  server.listen(PORT, () => {
    console.log("\n" + "=".repeat(50));
    console.log(` 🚀  ${appName}  (zero-dependency mode)`);
    console.log(` 📍  http://localhost:${PORT}`);
    console.log(` 🔧  ${env}`);
    console.log("=".repeat(50));
    console.log("\n 💡  To unlock Express + MongoDB:");
    console.log("    npm install express mongoose");
    console.log("    git add -A && git commit -m 'Add deps'");
    console.log("    git push build main\n");
  });

  process.on("SIGTERM", () => { console.log("\n👋  Shutting down…"); process.exit(0); });
}
